### ISSUE TITLE
Administrator creates user profiles

### ISSUE THREAD

**Issue by saturnflyer** [saturnflyer/purple_door#3]
Given an admin is logged in
And the admin visits the new user page
When the admin submits valid user data
Then the user receives an invitation to create a password and login

**Comment by mallorybucell** [comment]
data model/attributes

USER
- username
- password
- email
- first name
- last name
- DOB
- created_date (hire date)
- profile_image

*EVENTS Table (one to many)
- TYPE
  - sobriety
  - let go from program 
  - program completion
  - employment
- START DATE
- END DATE
- NOTES (text) add additional event
