### ISSUE TITLE
Add validations

### ISSUE THREAD

**Issue by GeekOnCoffee** [saturnflyer/purple_door#50]
Validate:
-  topic has a curriculum
- event has a user
- objective has a workshop id

I'm happy to add them, but want to make sure they're intended to be required

**Comment by saturnflyer** [comment]
:+1: thanks @GeekOnCoffee!
These make sense to me

**Comment by elight** [comment]
:+1:

**Comment by jcavena** [comment]
Good times. The way the topics are created they should never be w/o a curriculum. Probably a different conversation, but what is the delete strategy for children of a Topic node?
