### ISSUE TITLE
Employee completes worksheet

### ISSUE THREAD

**Issue by saturnflyer** [saturnflyer/purple_door#6]
1. Employee visits the schedule page
2. Employee visits the current topic
3. Employee adds answers to questions listed
4. Employee marks topic complete
5. Admin visits the Employee's completed topic
6. Admin adds notes
7. [Admin adds discussion comments](https://github.com/saturnflyer/purple_door/issues/8)
8. System notifies other admins of discussion comments
9. Employee views topic and sees admin notes

**Comment by mlpinit** [comment]
- Worksheet
  - title
  - summary
- Objectives
  - worksheet_id
  - description
- Question
  - description
  - worksheet_id
- UserWorksheet
  - worksheet_id
- QuestionAnswer
  - question_id
  - user_worksheet_id
  - description
